---
- name: Install basic packages
  action: apt pkg={{item}} state=latest
  register: kvminstalled
  sudo: yes
  with_items:
    - bridge-utils
    - mysql-client
    - qemu-kvm
    - libvirt-bin
    - pm-utils

- name: Setup Bridge interfaces
  when: kvminstalled|success
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=644
  sudo: yes

- name: Setup libvirtd config
  copy: src=libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
  sudo: yes

- name: Setup qemu config
  copy: src=qemu.conf dest=/etc/libvirt/qemu.conf owner=root group=root mode=644
  sudo: yes

- name: Fix libvirtd opts
  shell: sed -i -e 's/libvirtd_opts="-d"/libvirtd_opts="-d -l"/' /etc/init/libvirt-bin.conf
  sudo: yes
  notify:
    - Restart libvirt-bin
