---
- hosts: acsbox
  gather_facts: False
  user: bhaisaab
  roles:
    - common
    - cloudstack-nfs
    - cloudstack-kvm
  tasks:
    - name: Check if server is alive
      action: ping
  #  - include: base.yml

