---
- hosts: acsbox
  gather_facts: True
  user: bhaisaab
  roles:
    - common
    - cloudstack-kvm
    #- cloudstack-nfs
  tasks:
    - name: Check if server is alive
      action: ping
  #  - include: base.yml

