---
- hosts: acsbox
  gather_facts: True
  user: bhaisaab
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

  roles:
    - { role: common, kvm_host: true}
    - kvm
    - nfs
    # - mysql ## cloudstack module has a dependency on mysql
    - cloudstack
