---
- hosts: acsbox
  gather_facts: True
  user: bhaisaab
  tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
      sudo: yes

  roles:
    - common
    - kvm
    - nfs
    - mysql
    - cloudstack
