---
- name: Update APT package cache
  apt: update_cache=yes

- name: Install basic packages
  action: apt pkg={{item}} state=installed
  with_items:
  - nfs-kernel-server
  - quota

- name: setup nfs exports
  shell: echo "/export  *(rw,async,no_root_squash,no_subtree_check)" > /etc/exports

