---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install basic packages
  action: apt pkg={{item}} state=latest install_recommends=no
  with_items:
    - sudo
    - vim
    - tmux
    - htop
    - locales
    - rsync
    - tar
    - tzdata
    - openssh-client
    - ntp
    - ntpdate
    - build-essential
    - git
    - wget
    - curl
    - zsh
  sudo: yes
  notify:
    - Setup locale
    - Start NTP

- name: Install SSH server
  apt: pkg=openssh-server state=latest
  register: sshinstalled
  sudo: yes
  notify:
    - Start SSH

- name: Setup SSHD config
  when: sshinstalled|success
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=644
  sudo: yes
  notify:
    - Restart SSH

- name: Create user
  action: user name="{{ default_username }}" password="{{ default_userpass }}" home="/home/{{ default_username }}" shell="/bin/{{ default_shell }}" state=present groups=adm,sudo,bhaisaab append=yes
  sudo: yes
  run_once: true
  notify:
    #- Setup ssh publickey
    - Setup ohmyzsh
    #- Setup dotfiles
    #- Install dotfiles

